name: Build And Deploy

on:
  push:
    branches:
      - development

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install && npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            build
    env:
      NODE_ENV: development
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    env:
      BUCKET: developer.thenewboston.com
    needs:
      - build-dev
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: ls -al -R .
      - run: aws s3 sync . s3://$BUCKET --delete